### ISSUE TITLE
support for configuration file

### ISSUE THREAD

**Issue by dansan** [bepasty/bepasty-client-cli#16]
Load defaults for all arguments from a configuration file and overwritten values by given cmdline arguments.
* ignore `list`
* use default for `fname` only if piped input
* use default for `ftype` only as fallback if it cannot be magically detected

Questions:
* security for `token` - is chmod 600 for the file enough?
* file format?
* cmdline argument that triggers "store current cmdline arguments to the conffile"? (makes it less error prone for users, allows to use less human friendly file formats like json)

**Comment by dansan** [comment]
Hi,

can you indicate if you're considering this?

Thanks

**Comment by NotANormalNerd** [comment]
I will have a look this evening.

**Comment by dansan** [comment]
Hey,
could you have a look at the pull request (https://github.com/bepasty/bepasty-client-cli/pull/17) please? I pushed a commit (https://github.com/bepasty/bepasty-client-cli/pull/17/commits/cde11a2c6f677b459b630803afd20fb58cc9eecd) a week ago, that addresses all issues.
Thanks
